/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package hello_08

import com.mine.hello.*

class App {
    String getGreeting() {
        return 'Hello world.'
    }

    static void main(String[] args) {
        println new App().greeting
        def x = Utils.sum(2, 3)
        println "Sum: ${x}"
    }
}
